FROM ubuntu
WORKDIR /home
RUN	apt-get update
RUN	apt-get install -y ca-certificates curl
RUN	install -m 0755 -d /etc/apt/keyrings
RUN	curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
RUN	chmod a+r /etc/apt/keyrings/docker.asc
	
RUN	# Add the repository to Apt sources:
RUN	echo \
	  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
	  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
	  tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN	apt-get update
RUN	apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
CMD ["docker", "run", "hello-world"]
